name: strapi-webhook
version: 0.1.1
description: Strapi webhook service
package: strapi-webhook

port:
  grpc: 8080
  # proxy: 8081
  http: 8081

k8s:
  repository: docker.io/ezconnect/strapi-webhook
  service:
    http:
      host: strapi-webhook.ez-connect.net
  tls: ez-connect.net-tls
  volume: {}
    # strapi-webhook:
    #   class: manual
    #   size: 256Mi
    #   path: /app/data
    #   host: /mnt/strapi-webhook

models:
  - name: EntryRequest
    fields:
      - name: event
        type: string
      - name: created_at
        type: string
      - name: model
        type: string
      - name: entry
        type: google.protobuf.Struct
  - name: EntryContent
    fields:
      - name: id
        type: int64
      - name: locale
        type: string
      - name: model
        type: string
      - name: isSingleType
        type: bool
      - name: parent
        type: string
        description: parent dir
      - name: filename
        type: string
      - name: text
        type: string
  - name: EntryResponse
    fields:
      - name: request
        type: EntryRequest
      - name: response
        type: EntryContent
  - name: MediaRequest
    fields:
      - name: event
        type: string
      - name: media
        type: google.protobuf.Struct
      - name: url
        type: string
  - name: MediaContent
    fields:
      - name: url
        type: string
      - name: thumbnail
        type: string
      - name: small
        type: string
  - name: MediaResponse
    fields:
      - name: request
        type: MediaRequest
      - name: response
        type: MediaContent
  # # View an entry
  # - name: ViewRequest
  #   fields:
  #     - name: section
  #       type: string
  #     - name: id
  #       type: int64
  # - name: ViewResponse
  #   fields:
  #     - name: views
  #       type: int64
  
endpoints:
  - name: Entry
    request: EntryRequest
    response: EntryResponse
    http:
      path: /entry
      method: POST
  - name: Media
    request: MediaRequest
    response: MediaResponse
    http:
      path: /media
      method: POST
  # # Increase `views` field of an entry
  # - name: View
  #   request: ViewRequest
  #   response: ViewResponse
  #   http:
  #     path: /view
  #     method: POST