{{- $name := include "chart.fullname" . -}}
{{- $labels := include "chart.labels" . | nindent 4 -}}
{{- $selectorLabels := include "chart.selectorLabels" . | nindent 4 -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- $labels }}
spec:
  type: {{ .type }}
  ports:
    {{- range $k, $v := .Values.service }}
    - name: {{ $k }}
      port: {{ $v }}
      targetPort: {{ $v }}
    {{- end }}
  selector:
    {{- $selectorLabels }}
