{{- $name := include "chart.fullname" . -}}
{{- $labels := include "chart.labels" . | nindent 4 -}}
{{- $selectorLabels := include "chart.selectorLabels" . | nindent 4 -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  labels:
    {{- $labels }}
spec:
  type: {{ .type }}
  ports:
    {{- range .Values.service.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .port }}
      protocol: {{ .protocol }}
    {{- end }}
  selector:
    {{- $selectorLabels }}
