{{- $name := include "chart.fullname" . -}}

{{- if .Values.storage.persistent.enable }}
{{- with .Values.storage.persistent }}
# Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ $name }}
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: {{ .size }}
  accessModes:
    {{ toYaml .accessModes }}
  hostPath:
    path: {{ .hostPath }}

---
# Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $name }}
spec:
  storageClassName: manual
  accessModes:
    {{ toYaml .accessModes }}
  resources:
    requests:
      storage: {{ .size }}
{{- end }}
{{- end }}
