- name: Entry
  request: EntryRequest
  response: EntryResponse
  http:
    path: /entry
    method: POST
- name: Media
  request: MediaRequest
  response: MediaResponse
  http:
    path: /media
    method: POST
# # Increase `views` field of an entry
# - name: View
#   request: ViewRequest
#   response: ViewResponse
#   http:
#     path: /view
#     method: POST
