deployment:
  kind: Deployment
  replicas: 1
  image: docker.io/ezconnect/strapiwebhook
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  env:
    COLLECTION_TYPES: contributor,article,document,career,project,page,resume
    DEFAULT_LOCALE: en
    GIT_COMMIT: Sync CMS
    GIT_TIMEOUT: "300"
    HUGO_SITE_DIR: /home/webhook
    SINGLE_TYPES: site,home,nav,about
    STRAPI_API_TOKEN: api-token
    STRAPI_HOST: http://localhost:1337
  command: []
  args: []
  initContainers: []
  liveness: {}
  readiness: {}
service:
  type: ClusterIP
  ports:
    http:
      port: 8080
ingress:
  enabled: false
  hosts: {}
persistent:
  enabled: false
  volumes: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
affinity: {}
tolerations: []
resource: {}
autoscaling:
  enabled: false
  min: 1
  max: 3
  cpu: 0.5
  memory: 0.5
serviceAccount:
  enabled: false
