deployment:
  kind: Deployment
  replicas: 1
  image: docker.io/ezconnect/strapiwebhook
  imagePullSecrets: []
  pullPolicy: IfNotPresent
  env:
    CMD: echo 'build the site'; hugo --gc --minify;
    COLLECTION_TYPES: section,contributor,article,document,career,project,page,resume
    DEBOUNCED_CMD: echo 'debounced cmd'
    DEBOUNCED_TIMEOUT: 300
    DEFAULT_LOCALE: en
    SINGLE_TYPES: site,home,nav,about
    SITE_DIR: /home/web
    STRAPI_API_TOKEN: api-token
    STRAPI_HOST: http://localhost:1337
    TEMPLATE_DIR: /home/web/.config/template
  command: []
  args: []
  initContainers: []
  liveness: {}
  readiness: {}
service:
  type: ClusterIP
  ports:
    http:
      port: 8080
ingress:
  enabled: false
  hosts: {}
persistent:
  enabled: false
  volumes: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
affinity: {}
tolerations: []
resource: {}
autoscaling:
  enabled: false
  min: 1
  max: 3
  cpu: 0.5
  memory: 0.5
serviceAccount:
  enabled: false
